#ifndef iv_graphic_TA_insts_h
#define iv_graphic_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include <ta/typea.h>
#include <graphic.h>
#include <graphic_text.h>
#include <graphic_viewer.h>
#include "iv_graphic_TA_type.h"


extern	Xform*	TAI_Xform;
extern	taList<Xform>*	TAI_taList_Xform_;
extern	Xform_List*	TAI_Xform_List;


#endif // iv_graphic_TA_insts_h
