#ifndef xcss_TA_types_h
#define xcss_TA_types_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


class TypeDef;
extern void ta_Init_xcss();

extern TypeDef TA_XCssEvent;
extern TypeDef TA_taList_XCssEvent_;
extern TypeDef TA_const_XCssEvent;
extern TypeDef TA_const_XCssEvent_ref;
extern TypeDef TA_XCssEvent_List;
extern TypeDef TA_const_XCssEvent_List;
extern TypeDef TA_const_XCssEvent_List_ref;
extern TypeDef TA_XCss;
extern TypeDef TA_const_XCss;
extern TypeDef TA_const_XCss_ref;


#endif // xcss_TA_types_h
