#ifndef xcss_TA_insts_h
#define xcss_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include <ta/typea.h>
#include <xcss.h>
#include "xcss_TA_type.h"


extern	XCssEvent*	TAI_XCssEvent;
extern	taList<XCssEvent>*	TAI_taList_XCssEvent_;
extern	XCssEvent_List*	TAI_XCssEvent_List;
extern	XCss*	TAI_XCss;


#endif // xcss_TA_insts_h
