#ifndef lstm_TA_types_h
#define lstm_TA_types_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


class TypeDef;
extern void ta_Init_lstm();

extern TypeDef TA_LstmBpUnit;
extern TypeDef TA_MemBpUnit;
extern TypeDef TA_LstmBpUnit_ptr;
extern TypeDef TA_LstmBpConSpec;
extern TypeDef TA_const_LstmBpConSpec;
extern TypeDef TA_const_LstmBpConSpec_ref;
extern TypeDef TA_InGateToMemConSpec;
extern TypeDef TA_const_InGateToMemConSpec;
extern TypeDef TA_FrgGateToMemConSpec;
extern TypeDef TA_const_InGateToMemConSpec_ref;
extern TypeDef TA_MemBpUnit_ptr;
extern TypeDef TA_const_FrgGateToMemConSpec;
extern TypeDef TA_const_FrgGateToMemConSpec_ref;
extern TypeDef TA_OutGateToMemConSpec;
extern TypeDef TA_const_OutGateToMemConSpec;
extern TypeDef TA_const_OutGateToMemConSpec_ref;
extern TypeDef TA_DmemBpCon;
extern TypeDef TA_DmemBpCon_ptr;
extern TypeDef TA_const_DmemBpCon;
extern TypeDef TA_const_DmemBpCon_ref;
extern TypeDef TA_DmemBpConSpec;
extern TypeDef TA_const_DmemBpConSpec;
extern TypeDef TA_const_DmemBpConSpec_ref;
extern TypeDef TA_InGateInConSpec;
extern TypeDef TA_const_InGateInConSpec;
extern TypeDef TA_const_InGateInConSpec_ref;
extern TypeDef TA_FrgGateInConSpec;
extern TypeDef TA_const_FrgGateInConSpec;
extern TypeDef TA_const_FrgGateInConSpec_ref;
extern TypeDef TA_MemGateInConSpec;
extern TypeDef TA_const_MemGateInConSpec;
extern TypeDef TA_const_MemGateInConSpec_ref;
extern TypeDef TA_LstmBpUnitSpec;
extern TypeDef TA_const_LstmBpUnit;
extern TypeDef TA_const_LstmBpUnitSpec;
extern TypeDef TA_const_LstmBpUnit_ref;
extern TypeDef TA_const_LstmBpUnitSpec_ref;
extern TypeDef TA_DmemBpUnitSpec;
extern TypeDef TA_const_DmemBpUnitSpec;
extern TypeDef TA_MemBpUnitSpec;
extern TypeDef TA_const_DmemBpUnitSpec_ref;
extern TypeDef TA_const_MemBpUnit;
extern TypeDef TA_const_MemBpUnitSpec;
extern TypeDef TA_const_MemBpUnit_ref;
extern TypeDef TA_const_MemBpUnitSpec_ref;
extern TypeDef TA_LstmBpTrial;
extern TypeDef TA_const_LstmBpTrial;
extern TypeDef TA_const_LstmBpTrial_ref;


#endif // lstm_TA_types_h
