#ifndef cs_TA_types_h
#define cs_TA_types_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


class TypeDef;
extern void ta_Init_cs();

extern TypeDef TA_CsCon;
extern TypeDef TA_CsConSpec;
extern TypeDef TA_CsCon_Group;
extern TypeDef TA_CsUnitSpec;
extern TypeDef TA_SigmoidUnitSpec;
extern TypeDef TA_BoltzUnitSpec;
extern TypeDef TA_IACUnitSpec;
extern TypeDef TA_CsUnit;
extern TypeDef TA_CsSample;
extern TypeDef TA_CsTrial;
extern TypeDef TA_CsSettle;
extern TypeDef TA_CsCycle;
extern TypeDef TA_CsMaxDa;
extern TypeDef TA_CsDistStat;
extern TypeDef TA_CsTIGstat;
extern TypeDef TA_CsTargStat;
extern TypeDef TA_CsGoodStat;
extern TypeDef TA_const_CsCon;
extern TypeDef TA_const_CsCon_ref;
extern TypeDef TA_CsConSpec_ptr;
extern TypeDef TA_CsCon_ptr;
extern TypeDef TA_CsUnit_ptr;
extern TypeDef TA_CsCon_Group_ptr;
extern TypeDef TA_const_CsConSpec;
extern TypeDef TA_const_CsConSpec_ref;
extern TypeDef TA_const_CsCon_Group;
extern TypeDef TA_const_CsCon_Group_ref;
extern TypeDef TA_const_CsUnitSpec;
extern TypeDef TA_const_CsUnitSpec_ref;
extern TypeDef TA_const_SigmoidUnitSpec;
extern TypeDef TA_const_SigmoidUnitSpec_ref;
extern TypeDef TA_const_BoltzUnitSpec;
extern TypeDef TA_const_BoltzUnitSpec_ref;
extern TypeDef TA_const_IACUnitSpec;
extern TypeDef TA_const_IACUnitSpec_ref;
extern TypeDef TA_LinearCsUnitSpec;
extern TypeDef TA_const_LinearCsUnitSpec;
extern TypeDef TA_ThreshLinCsUnitSpec;
extern TypeDef TA_const_LinearCsUnitSpec_ref;
extern TypeDef TA_const_CsUnit;
extern TypeDef TA_const_ThreshLinCsUnitSpec;
extern TypeDef TA_const_CsUnit_ref;
extern TypeDef TA_const_ThreshLinCsUnitSpec_ref;
extern TypeDef TA_CsSettle_ptr;
extern TypeDef TA_CsTrial_ptr;
extern TypeDef TA_const_CsCycle;
extern TypeDef TA_const_CsCycle_ref;
extern TypeDef TA_const_CsSettle;
extern TypeDef TA_const_CsSettle_ref;
extern TypeDef TA_const_CsTrial;
extern TypeDef TA_const_CsTrial_ref;
extern TypeDef TA_const_CsSample;
extern TypeDef TA_const_CsSample_ref;
extern TypeDef TA_const_CsMaxDa;
extern TypeDef TA_const_CsMaxDa_ref;
extern TypeDef TA_const_CsDistStat;
extern TypeDef TA_const_CsDistStat_ref;
extern TypeDef TA_CsDistStat_ptr;
extern TypeDef TA_const_CsTIGstat;
extern TypeDef TA_const_CsTIGstat_ref;
extern TypeDef TA_const_CsTargStat;
extern TypeDef TA_const_CsTargStat_ref;
extern TypeDef TA_const_CsGoodStat;
extern TypeDef TA_const_CsGoodStat_ref;
extern TypeDef TA_HebbCsConSpec;
extern TypeDef TA_const_HebbCsConSpec;
extern TypeDef TA_const_HebbCsConSpec_ref;


#endif // cs_TA_types_h
