#ifndef pdp_TA_insts_h
#define pdp_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include <ta/typea.h>
#include <declare.h>
#include <base.h>
#include <spec.h>
#include <spec_tmplt.h>
#include <netstru.h>
#include <enviro.h>
#include <process.h>
#include <pdplog.h>
#include <stats.h>
#include <sched_proc.h>
#include <net_iv.h>
#include <pdp_iv.h>
#include <enviro_iv.h>
#include <netstru_extra.h>
#include <enviro_extra.h>
#include <procs_extra.h>
#include <pdpshell.h>
#include "pdp_TA_type.h"


extern	PDPView*	TAI_PDPView;
extern	BaseSpec*	TAI_BaseSpec;
extern	Process*	TAI_Process;
extern	SigmoidSpec*	TAI_SigmoidSpec;
extern	ConSpec*	TAI_ConSpec;
extern	Connection*	TAI_Connection;
extern	Con_Group*	TAI_Con_Group;
extern	UnitSpec*	TAI_UnitSpec;
extern	Unit*	TAI_Unit;
extern	ProjectionSpec*	TAI_ProjectionSpec;
extern	Projection*	TAI_Projection;
extern	LayerSpec*	TAI_LayerSpec;
extern	Layer*	TAI_Layer;
extern	Network*	TAI_Network;
extern	NetView*	TAI_NetView;
extern	Project*	TAI_Project;
extern	PDPRoot*	TAI_PDPRoot;
extern	EventSpec*	TAI_EventSpec;
extern	Pattern*	TAI_Pattern;
extern	Event*	TAI_Event;
extern	Environment*	TAI_Environment;
extern	ScriptEnv*	TAI_ScriptEnv;
extern	TimeEnvironment*	TAI_TimeEnvironment;
extern	Stat*	TAI_Stat;
extern	SE_Stat*	TAI_SE_Stat;
extern	MonitorStat*	TAI_MonitorStat;
extern	ClosestEventStat*	TAI_ClosestEventStat;
extern	CyclesToSettle*	TAI_CyclesToSettle;
extern	ScriptStat*	TAI_ScriptStat;
extern	CompareStat*	TAI_CompareStat;
extern	EpochCounterStat*	TAI_EpochCounterStat;
extern	ProcCounterStat*	TAI_ProcCounterStat;
extern	SchedProcess*	TAI_SchedProcess;
extern	BatchProcess*	TAI_BatchProcess;
extern	TrainProcess*	TAI_TrainProcess;
extern	NEpochProcess*	TAI_NEpochProcess;
extern	EpochProcess*	TAI_EpochProcess;
extern	SequenceProcess*	TAI_SequenceProcess;
extern	TrialProcess*	TAI_TrialProcess;
extern	SettleProcess*	TAI_SettleProcess;
extern	CycleProcess*	TAI_CycleProcess;
extern	SequenceEpoch*	TAI_SequenceEpoch;
extern	PDPLog*	TAI_PDPLog;
extern	TextLog*	TAI_TextLog;
extern	GraphLog*	TAI_GraphLog;
extern	GridLog*	TAI_GridLog;
extern	LogView*	TAI_LogView;
extern	TextLogView*	TAI_TextLogView;
extern	GraphLogView*	TAI_GraphLogView;
extern	GridLogView*	TAI_GridLogView;
extern	pdpMisc*	TAI_pdpMisc;
extern	PDPMGroup*	TAI_PDPMGroup;
extern	Event_MGroup*	TAI_Event_MGroup;
extern	BaseSpec_MGroup*	TAI_BaseSpec_MGroup;
extern	PosGroup*	TAI_PosGroup;
extern	PosMGroup*	TAI_PosMGroup;
extern	BaseSubSpec*	TAI_BaseSubSpec;
extern	PatternSpec*	TAI_PatternSpec;
extern	SpecPtr_impl*	TAI_SpecPtr_impl;
extern	SchedItem*	TAI_SchedItem;
extern	taList<SchedItem>*	TAI_taList_SchedItem_;
extern	Schedule*	TAI_Schedule;
extern	WeightLimits*	TAI_WeightLimits;
extern	SpecPtr<ConSpec>*	TAI_SpecPtr_ConSpec_;
extern	ConSpec_SPtr*	TAI_ConSpec_SPtr;
extern	taList<Unit>*	TAI_taList_Unit_;
extern	Unit_List*	TAI_Unit_List;
extern	SpecPtr<UnitSpec>*	TAI_SpecPtr_UnitSpec_;
extern	UnitSpec_SPtr*	TAI_UnitSpec_SPtr;
extern	SpecPtr<ProjectionSpec>*	TAI_SpecPtr_ProjectionSpec_;
extern	ProjectionSpec_SPtr*	TAI_ProjectionSpec_SPtr;
extern	Projection_Group*	TAI_Projection_Group;
extern	taGroup<Unit>*	TAI_taGroup_Unit_;
extern	Unit_Group*	TAI_Unit_Group;
extern	Layer_MGroup*	TAI_Layer_MGroup;
extern	NetViewLabel*	TAI_NetViewLabel;
extern	NetViewScaleRange*	TAI_NetViewScaleRange;
extern	taList<NetViewScaleRange>*	TAI_taList_NetViewScaleRange_;
extern	NetViewScaleRange_List*	TAI_NetViewScaleRange_List;
extern	NetViewGraphic*	TAI_NetViewGraphic;
extern	taList<NetViewGraphic>*	TAI_taList_NetViewGraphic_;
extern	NetViewGraphic_List*	TAI_NetViewGraphic_List;
extern	Network_MGroup*	TAI_Network_MGroup;
extern	EnviroView*	TAI_EnviroView;
extern	Pattern_Group*	TAI_Pattern_Group;
extern	PatternSpec_Group*	TAI_PatternSpec_Group;
extern	SpecPtr<EventSpec>*	TAI_SpecPtr_EventSpec_;
extern	EventSpec_SPtr*	TAI_EventSpec_SPtr;
extern	Environment_MGroup*	TAI_Environment_MGroup;
extern	taList<Environment>*	TAI_taList_Environment_;
extern	Environment_List*	TAI_Environment_List;
extern	DataItem*	TAI_DataItem;
extern	taList<DataItem>*	TAI_taList_DataItem_;
extern	DataItem_List*	TAI_DataItem_List;
extern	LogData*	TAI_LogData;
extern	CtrlPanelData*	TAI_CtrlPanelData;
extern	Process_Group*	TAI_Process_Group;
extern	Process_MGroup*	TAI_Process_MGroup;
extern	NetLogView*	TAI_NetLogView;
extern	PDPLog_Group*	TAI_PDPLog_Group;
extern	PDPLog_MGroup*	TAI_PDPLog_MGroup;
extern	NetLog*	TAI_NetLog;
extern	GraphLogViewLabel*	TAI_GraphLogViewLabel;
extern	CritParam*	TAI_CritParam;
extern	StatVal*	TAI_StatVal;
extern	StatVal_List*	TAI_StatVal_List;
extern	StatValAgg*	TAI_StatValAgg;
extern	AggStat*	TAI_AggStat;
extern	Stat_Group*	TAI_Stat_Group;
extern	Counter*	TAI_Counter;
extern	StepParams*	TAI_StepParams;
extern	InteractiveEpoch*	TAI_InteractiveEpoch;
extern	LayerNameEdit*	TAI_LayerNameEdit;
extern	taivProcess*	TAI_taivProcess;
extern	taivProcessRunBox*	TAI_taivProcessRunBox;
extern	taivSpecMember*	TAI_taivSpecMember;
extern	ProjViewState*	TAI_ProjViewState;
extern	ObjNameEdit*	TAI_ObjNameEdit;
extern	PatSpecEdit*	TAI_PatSpecEdit;
extern	ObjValueEdit*	TAI_ObjValueEdit;
extern	FullPrjnSpec*	TAI_FullPrjnSpec;
extern	TessEl*	TAI_TessEl;
extern	taList<TessEl>*	TAI_taList_TessEl_;
extern	TessEl_List*	TAI_TessEl_List;
extern	TesselPrjnSpec*	TAI_TesselPrjnSpec;
extern	OneToOnePrjnSpec*	TAI_OneToOnePrjnSpec;
extern	UniformRndPrjnSpec*	TAI_UniformRndPrjnSpec;
extern	PolarRndPrjnSpec*	TAI_PolarRndPrjnSpec;
extern	SymmetricPrjnSpec*	TAI_SymmetricPrjnSpec;
extern	LinkPrjnConPtr*	TAI_LinkPrjnConPtr;
extern	taList<LinkPrjnConPtr>*	TAI_taList_LinkPrjnConPtr_;
extern	LinkPrjnConPtr_List*	TAI_LinkPrjnConPtr_List;
extern	LinkPrjnSpec*	TAI_LinkPrjnSpec;
extern	ScriptPrjnSpec*	TAI_ScriptPrjnSpec;
extern	CustomPrjnSpec*	TAI_CustomPrjnSpec;
extern	GpFullPrjnSpec*	TAI_GpFullPrjnSpec;
extern	GpOneToOnePrjnSpec*	TAI_GpOneToOnePrjnSpec;
extern	RndGpOneToOnePrjnSpec*	TAI_RndGpOneToOnePrjnSpec;
extern	GpOneToManyPrjnSpec*	TAI_GpOneToManyPrjnSpec;
extern	GpTessEl*	TAI_GpTessEl;
extern	taList<GpTessEl>*	TAI_taList_GpTessEl_;
extern	GpTessEl_List*	TAI_GpTessEl_List;
extern	GpRndTesselPrjnSpec*	TAI_GpRndTesselPrjnSpec;
extern	TiledRFPrjnSpec*	TAI_TiledRFPrjnSpec;
extern	TiledGpRFPrjnSpec*	TAI_TiledGpRFPrjnSpec;
extern	InteractiveScriptEnv*	TAI_InteractiveScriptEnv;
extern	FreqEvent*	TAI_FreqEvent;
extern	FreqEnv*	TAI_FreqEnv;
extern	FreqEvent_MGroup*	TAI_FreqEvent_MGroup;
extern	TimeEvent*	TAI_TimeEvent;
extern	TimeEvent_MGroup*	TAI_TimeEvent_MGroup;
extern	FreqTimeEvent*	TAI_FreqTimeEvent;
extern	FreqTimeEvent_MGroup*	TAI_FreqTimeEvent_MGroup;
extern	FreqTimeEnv*	TAI_FreqTimeEnv;
extern	ProbPattern*	TAI_ProbPattern;
extern	ProbPatternSpec_Group*	TAI_ProbPatternSpec_Group;
extern	ProbEventSpec*	TAI_ProbEventSpec;
extern	XYPatternSpec*	TAI_XYPatternSpec;
extern	XYPattern*	TAI_XYPattern;
extern	XYSubPatternSpec*	TAI_XYSubPatternSpec;
extern	XYSubPattern*	TAI_XYSubPattern;
extern	GroupPatternSpec*	TAI_GroupPatternSpec;
extern	DurEvent*	TAI_DurEvent;
extern	FromFileEnv*	TAI_FromFileEnv;
extern	ScriptProcess*	TAI_ScriptProcess;
extern	SaveNetsProc*	TAI_SaveNetsProc;
extern	SaveWtsProc*	TAI_SaveWtsProc;
extern	LoadWtsProc*	TAI_LoadWtsProc;
extern	InitWtsProc*	TAI_InitWtsProc;
extern	SyncEpochProc*	TAI_SyncEpochProc;
extern	GridSearchBatch*	TAI_GridSearchBatch;
extern	SameSeedBatch*	TAI_SameSeedBatch;
extern	ForkProcess*	TAI_ForkProcess;
extern	BridgeProcess*	TAI_BridgeProcess;
extern	MultiEnvProcess*	TAI_MultiEnvProcess;
extern	PatternFlagProcess*	TAI_PatternFlagProcess;
extern	ActThreshRTStat*	TAI_ActThreshRTStat;
extern	ProjectionStat*	TAI_ProjectionStat;
extern	ComputeStat*	TAI_ComputeStat;
extern	CopyToEnvStat*	TAI_CopyToEnvStat;
extern	MaxActTrgStat*	TAI_MaxActTrgStat;
extern	UnitActRFStat*	TAI_UnitActRFStat;
extern	UnitActRFStatResetProc*	TAI_UnitActRFStatResetProc;
extern	UnitEventRFStat*	TAI_UnitEventRFStat;
extern	UniquePatStat*	TAI_UniquePatStat;
extern	TimeCounterStat*	TAI_TimeCounterStat;
extern	TimeCounterStatResetProc*	TAI_TimeCounterStatResetProc;
extern	DispDataEnvProc*	TAI_DispDataEnvProc;
extern	DispNetWeightsProc*	TAI_DispNetWeightsProc;
extern	ClearLogProc*	TAI_ClearLogProc;
extern	TypeDefault_MGroup*	TAI_TypeDefault_MGroup;
extern	LayerWizEl*	TAI_LayerWizEl;
extern	Wizard*	TAI_Wizard;
extern	Wizard_MGroup*	TAI_Wizard_MGroup;
extern	SelectEdit_MGroup*	TAI_SelectEdit_MGroup;
extern	taList<ProjViewState>*	TAI_taList_ProjViewState_;
extern	ProjViewState_List*	TAI_ProjViewState_List;
extern	Project_MGroup*	TAI_Project_MGroup;


#endif // pdp_TA_insts_h
