#ifndef oldlba_TA_insts_h
#define oldlba_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include <ta/typea.h>
#include <oldlba.h>
#include "oldlba_TA_type.h"


extern	LeabraCon*	TAI_LeabraCon;
extern	LeabraConSpec*	TAI_LeabraConSpec;
extern	LeabraBiasSpec*	TAI_LeabraBiasSpec;
extern	LeabraCon_Group*	TAI_LeabraCon_Group;
extern	LeabraUnitSpec*	TAI_LeabraUnitSpec;
extern	LeabraUnit*	TAI_LeabraUnit;
extern	LeabraInhib*	TAI_LeabraInhib;
extern	LeabraLayerSpec*	TAI_LeabraLayerSpec;
extern	LeabraUnit_Group*	TAI_LeabraUnit_Group;
extern	LeabraLayer*	TAI_LeabraLayer;
extern	LeabraCycle*	TAI_LeabraCycle;
extern	LeabraSettle*	TAI_LeabraSettle;
extern	LeabraTrial*	TAI_LeabraTrial;
extern	LeabraMaxDa*	TAI_LeabraMaxDa;
extern	WtScaleSpec*	TAI_WtScaleSpec;
extern	WtSigSpec*	TAI_WtSigSpec;
extern	LearnMixSpec*	TAI_LearnMixSpec;
extern	FixedSAvg*	TAI_FixedSAvg;
extern	SAvgCorSpec*	TAI_SAvgCorSpec;
extern	ActFunSpec*	TAI_ActFunSpec;
extern	SpikeFunSpec*	TAI_SpikeFunSpec;
extern	DepressSpec*	TAI_DepressSpec;
extern	OptThreshSpec*	TAI_OptThreshSpec;
extern	DtSpec*	TAI_DtSpec;
extern	LeabraChannels*	TAI_LeabraChannels;
extern	VChanSpec*	TAI_VChanSpec;
extern	PhaseSharpSpec*	TAI_PhaseSharpSpec;
extern	ActRegSpec*	TAI_ActRegSpec;
extern	VChanBasis*	TAI_VChanBasis;
extern	LeabraUnitChans*	TAI_LeabraUnitChans;
extern	taPtrList<LeabraUnit>*	TAI_taPtrList_LeabraUnit_;
extern	LeabraSort*	TAI_LeabraSort;
extern	KWTASpec*	TAI_KWTASpec;
extern	AdaptISpec*	TAI_AdaptISpec;
extern	ClampSpec*	TAI_ClampSpec;
extern	DecaySpec*	TAI_DecaySpec;
extern	LayerLinkSpec*	TAI_LayerLinkSpec;
extern	SpecPtr<LeabraLayerSpec>*	TAI_SpecPtr_LeabraLayerSpec_;
extern	LeabraLayerSpec_SPtr*	TAI_LeabraLayerSpec_SPtr;
extern	AvgMaxVals*	TAI_AvgMaxVals;
extern	KWTAVals*	TAI_KWTAVals;
extern	AdaptIVals*	TAI_AdaptIVals;
extern	InhibVals*	TAI_InhibVals;
extern	LayerLink*	TAI_LayerLink;
extern	taList<LayerLink>*	TAI_taList_LayerLink_;
extern	LayerLink_List*	TAI_LayerLink_List;
extern	LeabraSE_Stat*	TAI_LeabraSE_Stat;
extern	LeabraAeSE_Stat*	TAI_LeabraAeSE_Stat;
extern	LeabraGoodStat*	TAI_LeabraGoodStat;
extern	LeabraSharpStat*	TAI_LeabraSharpStat;
extern	WrongOnStat*	TAI_WrongOnStat;
extern	ACRewSpec*	TAI_ACRewSpec;
extern	LeabraACLayerSpec*	TAI_LeabraACLayerSpec;
extern	LeabraLinUnitSpec*	TAI_LeabraLinUnitSpec;
extern	CtxtUpdateSpec*	TAI_CtxtUpdateSpec;
extern	LeabraContextLayerSpec*	TAI_LeabraContextLayerSpec;
extern	GateSpec*	TAI_GateSpec;
extern	GateNoiseSpec*	TAI_GateNoiseSpec;
extern	LeabraGatedCtxLayerSpec*	TAI_LeabraGatedCtxLayerSpec;
extern	LeabraACMaintLayerSpec*	TAI_LeabraACMaintLayerSpec;
extern	PhaseOrderEventSpec*	TAI_PhaseOrderEventSpec;
extern	LeabraTimeUnit*	TAI_LeabraTimeUnit;
extern	LeabraTimeUnitSpec*	TAI_LeabraTimeUnitSpec;
extern	LeabraTimeCon_Group*	TAI_LeabraTimeCon_Group;
extern	TimeMixSpec*	TAI_TimeMixSpec;
extern	LeabraTimeConSpec*	TAI_LeabraTimeConSpec;
extern	LeabraNegBiasSpec*	TAI_LeabraNegBiasSpec;
extern	LeabraMaintConSpec*	TAI_LeabraMaintConSpec;
extern	LeabraNetConSpec*	TAI_LeabraNetConSpec;
extern	PhaseDWtConSpec*	TAI_PhaseDWtConSpec;
extern	PhaseDWtUnitSpec*	TAI_PhaseDWtUnitSpec;
extern	LeabraTabledConSpec*	TAI_LeabraTabledConSpec;
extern	TrialSynDepCon*	TAI_TrialSynDepCon;
extern	SynDepSpec*	TAI_SynDepSpec;
extern	TrialSynDepConSpec*	TAI_TrialSynDepConSpec;
extern	FastWtCon*	TAI_FastWtCon;
extern	FastWtSpec*	TAI_FastWtSpec;
extern	FastWtConSpec*	TAI_FastWtConSpec;
extern	LeabraNewHebbConSpec*	TAI_LeabraNewHebbConSpec;
extern	SigAmpSpec*	TAI_SigAmpSpec;
extern	LeabraSigHebbConSpec*	TAI_LeabraSigHebbConSpec;
extern	ScalarValSpec*	TAI_ScalarValSpec;
extern	ScalarValBias*	TAI_ScalarValBias;
extern	ScalarValLayerSpec*	TAI_ScalarValLayerSpec;
extern	ScalarValSelfPrjnSpec*	TAI_ScalarValSelfPrjnSpec;
extern	MarkerConSpec*	TAI_MarkerConSpec;
extern	DaModUnit*	TAI_DaModUnit;
extern	DaModSpec*	TAI_DaModSpec;
extern	DaModUnitSpec*	TAI_DaModUnitSpec;
extern	AvgExtRewSpec*	TAI_AvgExtRewSpec;
extern	OutErrSpec*	TAI_OutErrSpec;
extern	ExtRewSpec*	TAI_ExtRewSpec;
extern	ExtRewLayerSpec*	TAI_ExtRewLayerSpec;
extern	ExtRew_Stat*	TAI_ExtRew_Stat;
extern	TDRewPredConSpec*	TAI_TDRewPredConSpec;
extern	TDRewPredLayerSpec*	TAI_TDRewPredLayerSpec;
extern	TDRewIntegSpec*	TAI_TDRewIntegSpec;
extern	TDRewIntegLayerSpec*	TAI_TDRewIntegLayerSpec;
extern	TdLayerSpec*	TAI_TdLayerSpec;
extern	LVConSpec*	TAI_LVConSpec;
extern	LVSpec*	TAI_LVSpec;
extern	LVLayerSpec*	TAI_LVLayerSpec;
extern	PVConSpec*	TAI_PVConSpec;
extern	PVSpec*	TAI_PVSpec;
extern	PVLayerSpec*	TAI_PVLayerSpec;
extern	PVSLayerSpec*	TAI_PVSLayerSpec;
extern	PVLVDaSpec*	TAI_PVLVDaSpec;
extern	PVLVDaLayerSpec*	TAI_PVLVDaLayerSpec;
extern	PatchLayerSpec*	TAI_PatchLayerSpec;
extern	SNcMiscSpec*	TAI_SNcMiscSpec;
extern	SNcLayerSpec*	TAI_SNcLayerSpec;
extern	MatrixConSpec*	TAI_MatrixConSpec;
extern	MatrixBiasSpec*	TAI_MatrixBiasSpec;
extern	MatrixUnitSpec*	TAI_MatrixUnitSpec;
extern	ContrastSpec*	TAI_ContrastSpec;
extern	MatrixRndGoSpec*	TAI_MatrixRndGoSpec;
extern	MatrixRndGoThrSpec*	TAI_MatrixRndGoThrSpec;
extern	MatrixMiscSpec*	TAI_MatrixMiscSpec;
extern	MatrixLayerSpec*	TAI_MatrixLayerSpec;
extern	SNrThalLayerSpec*	TAI_SNrThalLayerSpec;
extern	PFCGateSpec*	TAI_PFCGateSpec;
extern	PFCLayerSpec*	TAI_PFCLayerSpec;
extern	LeabraWiz*	TAI_LeabraWiz;


#endif // oldlba_TA_insts_h
