#ifndef so_TA_types_h
#define so_TA_types_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


class TypeDef;
extern void ta_Init_so();

extern TypeDef TA_SoCon;
extern TypeDef TA_SoConSpec;
extern TypeDef TA_SoCon_Group;
extern TypeDef TA_SoUnit;
extern TypeDef TA_SoUnitSpec;
extern TypeDef TA_SoLayer;
extern TypeDef TA_SoLayerSpec;
extern TypeDef TA_const_SoCon;
extern TypeDef TA_const_SoCon_ref;
extern TypeDef TA_SoCon_ptr;
extern TypeDef TA_SoCon_Group_ptr;
extern TypeDef TA_const_SoConSpec;
extern TypeDef TA_const_SoConSpec_ref;
extern TypeDef TA_const_SoCon_Group;
extern TypeDef TA_const_SoCon_Group_ref;
extern TypeDef TA_const_SoUnitSpec;
extern TypeDef TA_const_SoUnitSpec_ref;
extern TypeDef TA_ThreshLinSoUnitSpec;
extern TypeDef TA_const_SoUnit;
extern TypeDef TA_const_ThreshLinSoUnitSpec;
extern TypeDef TA_const_SoUnit_ref;
extern TypeDef TA_const_ThreshLinSoUnitSpec_ref;
extern TypeDef TA_SoUnit_ptr;
extern TypeDef TA_SoLayer_ptr;
extern TypeDef TA_const_SoLayerSpec;
extern TypeDef TA_const_SoLayerSpec_ref;
extern TypeDef TA_SpecPtr_SoLayerSpec_;
extern TypeDef TA_SoLayerSpec_SPtr;
extern TypeDef TA_const_SoLayerSpec_SPtr;
extern TypeDef TA_const_SoLayer;
extern TypeDef TA_const_SoLayerSpec_SPtr_ref;
extern TypeDef TA_const_SoLayer_ref;
extern TypeDef TA_SoTrial;
extern TypeDef TA_const_SoTrial;
extern TypeDef TA_HebbConSpec;
extern TypeDef TA_const_SoTrial_ref;
extern TypeDef TA_const_HebbConSpec;
extern TypeDef TA_const_HebbConSpec_ref;
extern TypeDef TA_SoftMaxLayerSpec;
extern TypeDef TA_ClConSpec;
extern TypeDef TA_const_SoftMaxLayerSpec;
extern TypeDef TA_SoftClConSpec;
extern TypeDef TA_const_SoftMaxLayerSpec_ref;
extern TypeDef TA_ClLayerSpec;
extern TypeDef TA_SoftClUnitSpec;
extern TypeDef TA_const_ClConSpec;
extern TypeDef TA_const_ClConSpec_ref;
extern TypeDef TA_const_SoftClConSpec;
extern TypeDef TA_const_SoftClConSpec_ref;
extern TypeDef TA_const_ClLayerSpec;
extern TypeDef TA_const_ClLayerSpec_ref;
extern TypeDef TA_const_SoftClUnitSpec;
extern TypeDef TA_const_SoftClUnitSpec_ref;
extern TypeDef TA_SoftClLayerSpec;
extern TypeDef TA_const_SoftClLayerSpec;
extern TypeDef TA_SomUnitSpec;
extern TypeDef TA_const_SoftClLayerSpec_ref;
extern TypeDef TA_const_SomUnitSpec;
extern TypeDef TA_const_SomUnitSpec_ref;
extern TypeDef TA_NeighborEl;
extern TypeDef TA_taList_NeighborEl_;
extern TypeDef TA_const_NeighborEl;
extern TypeDef TA_const_NeighborEl_ref;
extern TypeDef TA_NeighborEl_List;
extern TypeDef TA_const_NeighborEl_List;
extern TypeDef TA_const_NeighborEl_List_ref;
extern TypeDef TA_SomLayerSpec;
extern TypeDef TA_const_SomLayerSpec;
extern TypeDef TA_const_SomLayerSpec_ref;
extern TypeDef TA_ZshConSpec;
extern TypeDef TA_const_ZshConSpec;
extern TypeDef TA_const_ZshConSpec_ref;
extern TypeDef TA_MaxInConSpec;
extern TypeDef TA_const_MaxInConSpec;
extern TypeDef TA_const_MaxInConSpec_ref;


#endif // so_TA_types_h
