#ifndef ta_misc_TA_insts_h
#define ta_misc_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include <ta/typea.h>
#include <win_base.h>
#include <win_base_tmplt.h>
#include <minmax.h>
#include <random.h>
#include <tdgeometry.h>
#include <aggregate.h>
#include <colorscale.h>
#include <array_iv.h>
#include <fontspec.h>
#include <datatable.h>
#include <datatable_tmplt.h>
#include <datatable_iv.h>
#include <ta_file.h>
#include <script_base.h>
#include <fun_lookup.h>
#include "ta_misc_TA_type.h"


extern	MenuGroup_impl*	TAI_MenuGroup_impl;
extern	WinGeometry*	TAI_WinGeometry;
extern	WinBase*	TAI_WinBase;
extern	WinView*	TAI_WinView;
extern	WinMgr*	TAI_WinMgr;
extern	winbMisc*	TAI_winbMisc;
extern	AnimImgCapture*	TAI_AnimImgCapture;
extern	WinView_Group*	TAI_WinView_Group;
extern	WinView_MGroup*	TAI_WinView_MGroup;
extern	MinMax*	TAI_MinMax;
extern	MinMaxRange*	TAI_MinMaxRange;
extern	FixedMinMax*	TAI_FixedMinMax;
extern	Modulo*	TAI_Modulo;
extern	MinMaxInt*	TAI_MinMaxInt;
extern	RndSeed*	TAI_RndSeed;
extern	Random*	TAI_Random;
extern	TimeUsed*	TAI_TimeUsed;
extern	TwoDCoord*	TAI_TwoDCoord;
extern	PosTwoDCoord*	TAI_PosTwoDCoord;
extern	TDCoord*	TAI_TDCoord;
extern	PosTDCoord*	TAI_PosTDCoord;
extern	FloatTwoDCoord*	TAI_FloatTwoDCoord;
extern	FloatTDCoord*	TAI_FloatTDCoord;
extern	ValIdx*	TAI_ValIdx;
extern	taArray<ValIdx>*	TAI_taArray_ValIdx_;
extern	ValIdx_Array*	TAI_ValIdx_Array;
extern	CountParam*	TAI_CountParam;
extern	Aggregate*	TAI_Aggregate;
extern	SimpleMathSpec*	TAI_SimpleMathSpec;
extern	RGBA*	TAI_RGBA;
extern	taList<RGBA>*	TAI_taList_RGBA_;
extern	RGBA_List*	TAI_RGBA_List;
extern	TAColor*	TAI_TAColor;
extern	taList<TAColor>*	TAI_taList_TAColor_;
extern	TAColor_List*	TAI_TAColor_List;
extern	ColorScaleSpec*	TAI_ColorScaleSpec;
extern	ColorScaleSpec_MGroup*	TAI_ColorScaleSpec_MGroup;
extern	gpivArrayC_Type*	TAI_gpivArrayC_Type;
extern	gpivArrayCEdit*	TAI_gpivArrayCEdit;
extern	FontSpec*	TAI_FontSpec;
extern	ViewLabel*	TAI_ViewLabel;
extern	taList<ViewLabel>*	TAI_taList_ViewLabel_;
extern	ViewLabel_List*	TAI_ViewLabel_List;
extern	float_RArray*	TAI_float_RArray;
extern	DataArray_impl*	TAI_DataArray_impl;
extern	taGroup<DataArray_impl>*	TAI_taGroup_DataArray_impl_;
extern	DataTable*	TAI_DataTable;
extern	ClustNode*	TAI_ClustNode;
extern	ClustLink*	TAI_ClustLink;
extern	DA_ViewSpec*	TAI_DA_ViewSpec;
extern	taGroup<DA_ViewSpec>*	TAI_taGroup_DA_ViewSpec_;
extern	DT_ViewSpec*	TAI_DT_ViewSpec;
extern	DA_TextViewSpec*	TAI_DA_TextViewSpec;
extern	DA_NetViewSpec*	TAI_DA_NetViewSpec;
extern	DA_GraphViewSpec*	TAI_DA_GraphViewSpec;
extern	DT_GraphViewSpec*	TAI_DT_GraphViewSpec;
extern	DA_GridViewSpec*	TAI_DA_GridViewSpec;
extern	DT_GridViewSpec*	TAI_DT_GridViewSpec;
extern	DataArray<float_RArray>*	TAI_DataArray_float_RArray_;
extern	float_Data*	TAI_float_Data;
extern	DataArray<String_Array>*	TAI_DataArray_String_Array_;
extern	String_Data*	TAI_String_Data;
extern	taFile*	TAI_taFile;
extern	ScriptBase*	TAI_ScriptBase;
extern	taPtrList<ScriptBase>*	TAI_taPtrList_ScriptBase_;
extern	ScriptBase_List*	TAI_ScriptBase_List;
extern	SArg_Array*	TAI_SArg_Array;
extern	SArgEdit*	TAI_SArgEdit;
extern	Script*	TAI_Script;
extern	Script_MGroup*	TAI_Script_MGroup;
extern	FunLookup*	TAI_FunLookup;
extern	FunLookupND*	TAI_FunLookupND;


#endif // ta_misc_TA_insts_h
