#ifndef bleabra_TA_insts_h
#define bleabra_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include <ta/typea.h>
#include <biobel.h>
#include <bleabra.h>
#include "bleabra_TA_type.h"


extern	BioBelCon*	TAI_BioBelCon;
extern	BioBelConSpec*	TAI_BioBelConSpec;
extern	BioBelCon_Group*	TAI_BioBelCon_Group;
extern	BioBelUnitSpec*	TAI_BioBelUnitSpec;
extern	BioBelUnit*	TAI_BioBelUnit;
extern	BioBelInhib*	TAI_BioBelInhib;
extern	BioBelLayerSpec*	TAI_BioBelLayerSpec;
extern	BioBelUnit_Group*	TAI_BioBelUnit_Group;
extern	BioBelLayer*	TAI_BioBelLayer;
extern	BioBelMaxDa*	TAI_BioBelMaxDa;
extern	BioBelChannels*	TAI_BioBelChannels;
extern	VChanSpecs*	TAI_VChanSpecs;
extern	ActFunSpecs*	TAI_ActFunSpecs;
extern	taPtrList<BioBelUnit>*	TAI_taPtrList_BioBelUnit_;
extern	BioBelSort*	TAI_BioBelSort;
extern	LayerLink*	TAI_LayerLink;
extern	taList<LayerLink>*	TAI_taList_LayerLink_;
extern	LayerLink_List*	TAI_LayerLink_List;
extern	AvgMaxVals*	TAI_AvgMaxVals;
extern	BioBelDecays*	TAI_BioBelDecays;
extern	KWTASpec*	TAI_KWTASpec;
extern	KWTAVals*	TAI_KWTAVals;
extern	ActInhibSpec*	TAI_ActInhibSpec;
extern	InhibVals*	TAI_InhibVals;
extern	SpecPtr<BioBelLayerSpec>*	TAI_SpecPtr_BioBelLayerSpec_;
extern	BioBelLayerSpec_SPtr*	TAI_BioBelLayerSpec_SPtr;
extern	LeabraCon*	TAI_LeabraCon;
extern	LeabraConSpec*	TAI_LeabraConSpec;
extern	LeabraBiasSpec*	TAI_LeabraBiasSpec;
extern	LeabraCon_Group*	TAI_LeabraCon_Group;
extern	LeabraUnitSpec*	TAI_LeabraUnitSpec;
extern	LeabraUnit*	TAI_LeabraUnit;
extern	LeabraLayer*	TAI_LeabraLayer;
extern	LeabraLayerSpec*	TAI_LeabraLayerSpec;
extern	LeabraCycle*	TAI_LeabraCycle;
extern	LeabraSettle*	TAI_LeabraSettle;
extern	LeabraTrial*	TAI_LeabraTrial;
extern	CascadeParams*	TAI_CascadeParams;
extern	LeabraAeSE_Stat*	TAI_LeabraAeSE_Stat;
extern	PhaseOrderEventSpec*	TAI_PhaseOrderEventSpec;
extern	LeabraHistUnit*	TAI_LeabraHistUnit;
extern	LeabraHistUnitSpec*	TAI_LeabraHistUnitSpec;
extern	LeabraHistConSpec*	TAI_LeabraHistConSpec;


#endif // bleabra_TA_insts_h
