#ifndef bpso_TA_insts_h
#define bpso_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include <ta/typea.h>
#include <bpso.h>
#include "bpso_TA_type.h"




#endif // bpso_TA_insts_h
