#ifndef ta_lib_min_TA_insts_h
#define ta_lib_min_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include <ta/typea.h>
#include <strstream-g++-3.1.h>
#include <ta_string.h>
#include <ta_stdef.h>
#include <ta_list.h>
#include <ta_list_tmplt.h>
#include <typea.h>
#include <ta_base.h>
#include <ta_base_tmplt.h>
#include <ta_group.h>
#include <ta_group_tmplt.h>
#include <ta_dump.h>
#include <tdefaults.h>
#include "ta_lib_min_TA_type.h"


extern	taBase*	TAI_taBase;
extern	taPtrList<taHashEl>*	TAI_taPtrList_taHashEl_;
extern	taPtrList<taHashBucket>*	TAI_taPtrList_taHashBucket_;
extern	taBase**	TAI_TAPtr;
extern	taPlainArray<taString>*	TAI_taPlainArray_taString_;
extern	taPlainArray<int>*	TAI_taPlainArray_int_;
extern	taMisc*	TAI_taMisc;
extern	taPtrList<EnumDef>*	TAI_taPtrList_EnumDef_;
extern	EnumDef*	TAI_EnumDef;
extern	EnumSpace*	TAI_EnumSpace;
extern	taPtrList<void>*	TAI_taPtrList_void_;
extern	TokenSpace*	TAI_TokenSpace;
extern	taPtrList<MemberDef>*	TAI_taPtrList_MemberDef_;
extern	MemberSpace*	TAI_MemberSpace;
extern	taPtrList<MethodDef>*	TAI_taPtrList_MethodDef_;
extern	MethodSpace*	TAI_MethodSpace;
extern	taPtrList<TypeDef>*	TAI_taPtrList_TypeDef_;
extern	TypeSpace*	TAI_TypeSpace;
extern	tabMisc*	TAI_tabMisc;
extern	taNBase*	TAI_taNBase;
extern	taNBase**	TAI_TANPtr;
extern	taOBase*	TAI_taOBase;
extern	taPtrList_base<taBase>*	TAI_taPtrList_base_taBase_;
extern	taList_impl*	TAI_taList_impl;
extern	taArray_base*	TAI_taArray_base;
extern	taList<taBase>*	TAI_taList_taBase_;
extern	taBase_List*	TAI_taBase_List;
extern	taArray<int>*	TAI_taArray_int_;
extern	int_Array*	TAI_int_Array;
extern	taArray<float>*	TAI_taArray_float_;
extern	float_Array*	TAI_float_Array;
extern	taArray<double>*	TAI_taArray_double_;
extern	double_Array*	TAI_double_Array;
extern	taArray<taString>*	TAI_taArray_taString_;
extern	String_Array*	TAI_String_Array;
extern	taArray<long>*	TAI_taArray_long_;
extern	long_Array*	TAI_long_Array;
extern	voidptr_Array*	TAI_voidptr_Array;
extern	taGroup_impl*	TAI_taGroup_impl;
extern	taList<taGroup_impl>*	TAI_taList_taGroup_impl_;
extern	TALOG*	TAI_TALOG;
extern	taSubGroup*	TAI_taSubGroup;
extern	DMemShareVar*	TAI_DMemShareVar;
extern	DMemShare*	TAI_DMemShare;
extern	taGroup<taBase>*	TAI_taGroup_taBase_;
extern	taBase_Group*	TAI_taBase_Group;
extern	taPtrList<VPUnref>*	TAI_taPtrList_VPUnref_;
extern	taPtrList<DumpPathSub>*	TAI_taPtrList_DumpPathSub_;
extern	taPtrList<DumpPathToken>*	TAI_taPtrList_DumpPathToken_;
extern	NameValue*	TAI_NameValue;
extern	TypeDefault*	TAI_TypeDefault;


#endif // ta_lib_min_TA_insts_h
