#ifndef lstm_TA_insts_h
#define lstm_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include <ta/typea.h>
#include <lstm.h>
#include "lstm_TA_type.h"


extern	LstmBpUnit*	TAI_LstmBpUnit;
extern	MemBpUnit*	TAI_MemBpUnit;
extern	LstmBpConSpec*	TAI_LstmBpConSpec;
extern	InGateToMemConSpec*	TAI_InGateToMemConSpec;
extern	FrgGateToMemConSpec*	TAI_FrgGateToMemConSpec;
extern	OutGateToMemConSpec*	TAI_OutGateToMemConSpec;
extern	DmemBpCon*	TAI_DmemBpCon;
extern	DmemBpConSpec*	TAI_DmemBpConSpec;
extern	InGateInConSpec*	TAI_InGateInConSpec;
extern	FrgGateInConSpec*	TAI_FrgGateInConSpec;
extern	MemGateInConSpec*	TAI_MemGateInConSpec;
extern	LstmBpUnitSpec*	TAI_LstmBpUnitSpec;
extern	DmemBpUnitSpec*	TAI_DmemBpUnitSpec;
extern	MemBpUnitSpec*	TAI_MemBpUnitSpec;
extern	LstmBpTrial*	TAI_LstmBpTrial;


#endif // lstm_TA_insts_h
