#ifndef rns_TA_insts_h
#define rns_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include <ta/typea.h>
#include <rns.h>
#include "rns_TA_type.h"


extern	RtCon*	TAI_RtCon;
extern	RtCon_Group*	TAI_RtCon_Group;
extern	RtUnit*	TAI_RtUnit;
extern	ModelParam*	TAI_ModelParam;
extern	RtUnitSpec*	TAI_RtUnitSpec;
extern	RtTrial*	TAI_RtTrial;
extern	float_DelayBuffer*	TAI_float_DelayBuffer;
extern	RtEvent*	TAI_RtEvent;
extern	NeuroModInfo*	TAI_NeuroModInfo;
extern	NMDAInfo*	TAI_NMDAInfo;
extern	HabitInfo*	TAI_HabitInfo;
extern	ActInfo*	TAI_ActInfo;
extern	ActTraceInfo*	TAI_ActTraceInfo;
extern	RecExcInfo*	TAI_RecExcInfo;
extern	SoftClampInfo*	TAI_SoftClampInfo;
extern	NormInfo*	TAI_NormInfo;
extern	SpikeInfo*	TAI_SpikeInfo;
extern	RandLearnInfoSpec*	TAI_RandLearnInfoSpec;
extern	VectAssocMapInfo*	TAI_VectAssocMapInfo;
extern	SigFuncInfo*	TAI_SigFuncInfo;
extern	EligTraceInfo*	TAI_EligTraceInfo;
extern	ModLearnInfo*	TAI_ModLearnInfo;
extern	ModLearnDecayInfo*	TAI_ModLearnDecayInfo;
extern	ExcludeNormInfo*	TAI_ExcludeNormInfo;
extern	RtConSpec*	TAI_RtConSpec;
extern	RtEpoch*	TAI_RtEpoch;
extern	Trigger*	TAI_Trigger;
extern	ResponseStat*	TAI_ResponseStat;
extern	TriggerCondition*	TAI_TriggerCondition;
extern	TransitionProb*	TAI_TransitionProb;
extern	taGroup<TransitionProb>*	TAI_taGroup_TransitionProb_;
extern	TransitionProb_Group*	TAI_TransitionProb_Group;
extern	eventTransition*	TAI_eventTransition;
extern	RtPatternSpec*	TAI_RtPatternSpec;
extern	NextEventInfo*	TAI_NextEventInfo;
extern	taGroup<Trigger>*	TAI_taGroup_Trigger_;
extern	Trigger_Group*	TAI_Trigger_Group;
extern	taGroup<NextEventInfo>*	TAI_taGroup_NextEventInfo_;
extern	NextEventInfo_Group*	TAI_NextEventInfo_Group;
extern	RtEventSpec*	TAI_RtEventSpec;
extern	RtConstraintInfo*	TAI_RtConstraintInfo;
extern	RtConstraintInfo_Group*	TAI_RtConstraintInfo_Group;
extern	RtConstraintSpec*	TAI_RtConstraintSpec;
extern	FitDataInfo*	TAI_FitDataInfo;
extern	FitDataInfo_Group*	TAI_FitDataInfo_Group;
extern	FitDataSpec*	TAI_FitDataSpec;
extern	optim*	TAI_optim;
extern	simplex*	TAI_simplex;
extern	subplex*	TAI_subplex;
extern	RtDistFitMgr*	TAI_RtDistFitMgr;
extern	RtConstrain*	TAI_RtConstrain;
extern	MPESubNameSpec*	TAI_MPESubNameSpec;
extern	MPELimitSpec*	TAI_MPELimitSpec;
extern	ModelParamEntry*	TAI_ModelParamEntry;
extern	taGroup<ModelParamEntry>*	TAI_taGroup_ModelParamEntry_;
extern	ModelParamEntry_Group*	TAI_ModelParamEntry_Group;


#endif // rns_TA_insts_h
