#ifndef iv_graphic_TA_types_h
#define iv_graphic_TA_types_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


class TypeDef;
extern void ta_Init_iv_graphic();

extern TypeDef TA_GlyphViewer;
extern TypeDef TA_Tool;
extern TypeDef TA_Tool_ref;
extern TypeDef TA_const_ivBrush_ptr;
extern TypeDef TA_const_ivFont_ptr;
extern TypeDef TA_ivCoord_ptr;
extern TypeDef TA_ivCoord_ptr_ref;
extern TypeDef TA_PointObj_ref;
extern TypeDef TA_BoxObj_ref;
extern TypeDef TA_const_ivCoord;
extern TypeDef TA_const_ivCoord_ptr;
extern TypeDef TA_const_ivCoord_ptr_ref;
extern TypeDef TA_Graphic;
extern TypeDef TA_PolyGraphic;
extern TypeDef TA_Graphic_ref;
extern TypeDef TA_Graphic_ptr;
extern TypeDef TA_GlyphViewer_ptr;
extern TypeDef TA_GraphicMaster;
extern TypeDef TA_Line;
extern TypeDef TA_Rectangle;
extern TypeDef TA_Circle;
extern TypeDef TA_Ellipse;
extern TypeDef TA_Open_BSpline;
extern TypeDef TA_Open_BSpline_ptr;
extern TypeDef TA_Closed_BSpline;
extern TypeDef TA_Polyline;
extern TypeDef TA_Closed_BSpline_ptr;
extern TypeDef TA_Polygon;
extern TypeDef TA_Text;
extern TypeDef TA_Xform;
extern TypeDef TA_taList_Xform_;
extern TypeDef TA_const_Xform;
extern TypeDef TA_const_Xform_ref;
extern TypeDef TA_Xform_List;
extern TypeDef TA_GraphicMaster_ptr;
extern TypeDef TA_const_Xform_List;
extern TypeDef TA_const_Xform_List_ref;
extern TypeDef TA_NoScale_Text_G;
extern TypeDef TA_ivAllocation_ref;
extern TypeDef TA_ivCursor_ptr;
extern TypeDef TA_ivCursor;
extern TypeDef TA_ToolState_ptr;
extern TypeDef TA_ToolState;
extern TypeDef TA_ivTransformer_ptr;
extern TypeDef TA_ivTransformer_ref;
extern TypeDef TA_Alignment;
extern TypeDef TA_DynamicLabel_ptr;
extern TypeDef TA_DynamicLabel;


#endif // iv_graphic_TA_types_h
