#ifndef cs_TA_insts_h
#define cs_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include <ta/typea.h>
#include <cs.h>
#include "cs_TA_type.h"


extern	CsCon*	TAI_CsCon;
extern	CsConSpec*	TAI_CsConSpec;
extern	CsCon_Group*	TAI_CsCon_Group;
extern	CsUnitSpec*	TAI_CsUnitSpec;
extern	SigmoidUnitSpec*	TAI_SigmoidUnitSpec;
extern	BoltzUnitSpec*	TAI_BoltzUnitSpec;
extern	IACUnitSpec*	TAI_IACUnitSpec;
extern	CsUnit*	TAI_CsUnit;
extern	CsSample*	TAI_CsSample;
extern	CsTrial*	TAI_CsTrial;
extern	CsSettle*	TAI_CsSettle;
extern	CsCycle*	TAI_CsCycle;
extern	CsMaxDa*	TAI_CsMaxDa;
extern	CsDistStat*	TAI_CsDistStat;
extern	CsTIGstat*	TAI_CsTIGstat;
extern	CsTargStat*	TAI_CsTargStat;
extern	CsGoodStat*	TAI_CsGoodStat;
extern	LinearCsUnitSpec*	TAI_LinearCsUnitSpec;
extern	ThreshLinCsUnitSpec*	TAI_ThreshLinCsUnitSpec;
extern	HebbCsConSpec*	TAI_HebbCsConSpec;


#endif // cs_TA_insts_h
