#ifndef so_TA_insts_h
#define so_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include <ta/typea.h>
#include <so.h>
#include <cl.h>
#include <som.h>
#include <zsh.h>
#include "so_TA_type.h"


extern	SoCon*	TAI_SoCon;
extern	SoConSpec*	TAI_SoConSpec;
extern	SoCon_Group*	TAI_SoCon_Group;
extern	SoUnit*	TAI_SoUnit;
extern	SoUnitSpec*	TAI_SoUnitSpec;
extern	SoLayer*	TAI_SoLayer;
extern	SoLayerSpec*	TAI_SoLayerSpec;
extern	ThreshLinSoUnitSpec*	TAI_ThreshLinSoUnitSpec;
extern	SpecPtr<SoLayerSpec>*	TAI_SpecPtr_SoLayerSpec_;
extern	SoLayerSpec_SPtr*	TAI_SoLayerSpec_SPtr;
extern	SoTrial*	TAI_SoTrial;
extern	HebbConSpec*	TAI_HebbConSpec;
extern	SoftMaxLayerSpec*	TAI_SoftMaxLayerSpec;
extern	ClConSpec*	TAI_ClConSpec;
extern	SoftClConSpec*	TAI_SoftClConSpec;
extern	ClLayerSpec*	TAI_ClLayerSpec;
extern	SoftClUnitSpec*	TAI_SoftClUnitSpec;
extern	SoftClLayerSpec*	TAI_SoftClLayerSpec;
extern	SomUnitSpec*	TAI_SomUnitSpec;
extern	NeighborEl*	TAI_NeighborEl;
extern	taList<NeighborEl>*	TAI_taList_NeighborEl_;
extern	NeighborEl_List*	TAI_NeighborEl_List;
extern	SomLayerSpec*	TAI_SomLayerSpec;
extern	ZshConSpec*	TAI_ZshConSpec;
extern	MaxInConSpec*	TAI_MaxInConSpec;


#endif // so_TA_insts_h
