default:
	g++ -fPIC -O2 -fno-exceptions -fno-rtti -Wall -Winline -DLINUX -c pdp++base.cc -o pdp++base.o
	g++ -fPIC -O2 -fno-exceptions -fno-rtti -Wall -Winline -DLINUX -c pdp++bench.cc -o pdp++bench.o

clean:
	/bin/rm *.o pdp++bench *.log *~

